[env:m5stack-stamps3]
platform = espressif32@6.12.0
board = m5stack-stamps3
framework = arduino
monitor_speed = 115200
board_build.flash_size = 8MB
board_upload.flash_size = 8MB
board_build.partitions = default_8MB.csv
lib_deps =
  https://github.com/m5stack/M5Cardputer.git#f1392858b9994c3547120e602a57d3553d16ab01
  https://github.com/m5stack/M5Unified.git#8530f5377d782e4a25a6c482de2e71c3f75ca8eb
  https://github.com/m5stack/M5GFX.git#d91077b9a607b59404e4e4a49f775c792bfae382
build_flags =
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MODE=1
  -DCORE_DEBUG_LEVEL=0
